date.timezone = "Asia/Tokyo"

; Laravel9 推奨設定
memory_limit = 512M
post_max_size = 100M
upload_max_filesize = 100M
max_execution_time = 300

; --------------------------------------------------
; mbstring
; Laravel9ではUTF-8が基本だが、
; 保守・運用でShift_JIS等を扱う可能性を考慮して残す。
; --------------------------------------------------
[mbstring]
mbstring.encoding_translation = Off
mbstring.detect_order = "UTF-8,SJIS,EUC-JP,JIS,ASCII"
